systemYaml: |
  shared: 
    node: 127.0.0.1

postgresql:

  enabled: true

  postgresqlPassword: PAssword123,.

databaseUpgradeReady: true

unifiedUpgradeAllowed: true

artifactory:

  masterKeySecretName: my-masterkey-secret

  joinKeySecretName: my-joinkey-secret

  license: 
    secret: artifactory-cluster-license
    dataKey: art.lic
nginx:

  enabled: false

ingress:

  enabled: true

  defaultBackend:

    enabled: true

  hosts: 

    - tooling.artifactory.ladifa.xyz

  routerPath: /

  artifactoryPath: /artifactory/

  className: ""

  annotations: 

    kubernetes.io/ingress.class: "nginx"

    nginx.ingress.kubernetes.io/proxy-body-size: "0"

    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"

    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"

    nginx.ingress.kubernetes.io/proxy-body-size: "0"

    nginx.ingress.kubernetes.io/rewrite-target: "/"

    nginx.ingress.kubernetes.io/configuration-snippet: |

      rewrite ^/(v2)/token /artifactory/api/docker/null/v2/token;

      rewrite ^/(v2)/([^\/]*)/(.*) /artifactory/api/docker/$2/$1/$3;

  tls: 

  - secretName: nginx-tls

    hosts:

            - tooling.artifactory.ladifa.xyz
